
dist: trusty
sudo: required

language: c

compiler:
    - gcc
#    - clang

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - gcc-9
            - cmake
            - cmake-data
            - valgrind

before_script:
    - echo "before script"
    - gcc --version
    - gcc-9 --version
    - valgrind --version
    
script: 
    - CC=gcc-9 cmake -H. -Bbuild
    - (cd build/ && CC=gcc-9 cmake --build .)

after_success:
    - cd build
    - ./attache-test
    - valgrind ./attache-test
    - valgrind --leak-check=full -v --track-origins=yes ./attache-test

